### PR TITLE
Migration to VCVRack v1 API

### PR DESCRIPTION
**Pull request by dizzisound**
@NonLinearInstruments 
Hi Ignasi, I completed a full migration of your plugin to Rack v1 API. 
I successfully tested the plugin on Windows, where it now builds with no warnings, and I just posted a Windows release in my forked repo: 
https://github.com/dizzisound/NLNRI_VCVRackPlugins/releases/tag/1.0 
Should you accept this PR, the plugin could be tested on Linux/Mac and hopefully find its way in the new VCVRack Library Manager.

### CODE REVIEW

**Comment by NonLinearInstruments** [comment]
Wow !! Daniele, this made my day !! ... I've been lost in other worlds and
had no time to keep updating these my little dear instruments. I thank You
very much for taking the time to do it. I've merged your pull request to
the main branch, hope this helps and if I can assist you in anything else
I'll be glad to do it.
Thanks again and stay safe :)

**Comment by dizzisound** [comment]
@NonLinearInstruments 

> I've been lost in other worlds [...]

Ah, I know the thing, it's 2020 after all (though 2019 was the same to me...)

Well, now hopefully the good and willing people at the Community Forum or the Facebook User group can test both Mac and Linux builds, and if they complete fluently you could issue a PR in the new [Library Manager](https://library.vcvrack.com/), did you see how long has it gone? It looks like a stunning music-nerdish heaven to me!

However, I can push for collaborative builds & testing in the Community, where you can look at this thread: https://community.vcvrack.com/t/plugin-authors-help-migrating-existing-plugins-to-rack-v1/3463/114

Then, if your plugin builds and works on all platforms, you can submit your PR to the VCVRack team, following the guidelines described here: 
https://github.com/VCVRack/library#adding-your-plugin-to-the-vcv-library-for-open-source-plugins

I also see you already have a dedicated plugin space here: https://github.com/VCVRack/library/issues/420, so you should be able to reuse that issue for your request to be reopened and solved.

Last thing, check for the `plugin.json` file, I filled it with data for you, trying to inferring attributes from the legacy version, but it's definitely your custom plugin' author-signing, so double check the _slug_, and _brand_, and URL's, and optionally update them with your latest/desired data. I think the `slug `especially act as a constrain for future releases or updates.

Here in Italy it's 9PM, I guess it's the same in Barcelona, so I wish you good evening, with moderate movida... we know how it is these days.

**Comment by NonLinearInstruments** [comment]
Hi, I'm sorry but I really have no spare time to dig into this ... may be if you are added as co-owner on the repository could kindly do it yourself ?

**Comment by dizzisound** [comment]
Hi Ignasi, thank you for your invite, I accepted the collaboration, though I will have really little spare time for maintenance or user support. 

Anyway, the only relevant point of decision now is whether you wish that the plugin will be featured/published again in the Rack Library Manager. In this case, I'll have to take 2 simple steps:
1) Check for cross-platform builds, with support from Community or trying to go with the CI/CB workflow-facilities way.
2) Submit a PR to the VCVRack Support Team for adoption in the Library Manager.

Let me know if you wish I proceed and take care of completing the above steps, or instead you prefer not to publish your plugin, and simply let people manually download and build it at their will, as they were already able to do until now.

**Comment by dizzisound** [comment]
@NonLinearInstruments  Good news, I was notified that the plugin passed all of the integration tests, so it's free to jump directly to step 2, submitting the new version in your dedicated plugin issue tracking area, here: https://github.com/VCVRack/library/issues/420
I keep waiting for you to let me possibly proceed on your behalf, and if it's the case, whether you want to switch back licensing to "BSD-3-Clause" as I just noticed that it was the original licensing clause you specified for your work.

**Comment by NonLinearInstruments** [comment]
Hi Danielle, I'm Ok you proceed on my behalf ... for the licence type, I
really do not remember why I used BSD-3-Clause but I'm ok also to use the
one you selected. Thanks again and stay safe :)

**Comment by dizzisound** [comment]
Hi Alvari, so I submitted the PR to the Library, targeting the plugin, as-is:
https://github.com/VCVRack/library/issues/420
You are obviously free to update or change your metadata in the `plugin.json` at your will, and submit subsequent PR's with a minor version bump. 
The Rack Support team will reopen the issue to process it, and you should be notified whether the plugin has been integrated in the Library, that usually happens in a few days, if no issues raise in the final process of validation.
Thanks, and take care :-)

**Pull request merged**
